### ISSUE TITLE
parsemail 2.0 does not work with Django 1.8

### ISSUE THREAD

**Issue by tmonjalo** [getpatchwork/patchwork#187]
When testing patchwork 2.0.2 with Python 2.7 and Django 1.8.19,
there was an error with "related_query_name":

```
# patchwork/bin/parsemail.sh <mbox

Traceback (most recent call last):
  File "patchwork/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "patchwork/patchwork/management/commands/parsemail.py", line 29, in <module>
    from patchwork.parser import parse_mail
  File "patchwork/patchwork/parser.py", line 34, in <module>
    from patchwork.models import Comment
  File "patchwork/patchwork/models.py", line 576, in <module>
    class Comment(EmailMixin, models.Model):
  File "patchwork/patchwork/models.py", line 581, in Comment
    on_delete=models.CASCADE)
  File "/usr/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 957, in __init__
    Field.__init__(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'related_query_name'
```

**Comment by stephenfin** [comment]
I think this is also an issue with your environment. This appears to be an issue if using Django < 1.7. See [here](https://github.com/mvpdev/django-eav/issues/31) for more information.
