### ISSUE TITLE
debug logging module not found

### ISSUE THREAD

**Issue by tmonjalo** [getpatchwork/patchwork#188]
My environment:
Python-2.7
Django-1.10
django-filter-1.0.4
djangorestframework-3.6.4
psycopg2-2.7.4
sqlparse-0.2.3
uWSGI-2.0.17

I see this error when running parsemail:

```
(virtualenv-patchwork-2.0)# patchwork/bin/parsemail.sh <mbox

Traceback (most recent call last):
  File "patchwork/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 252, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 135, in __init__
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 777, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 562, in configure
    'filter %r: %s' % (name, e))
ValueError: Unable to configure filter 'require_debug_true': Cannot resolve 'django.utils.log.RequireDebugTrue': No module named RequireDebugTrue
```

The workaround is this patch:

```
--- a/patchwork/settings/base.py
+++ b/patchwork/settings/base.py
@@ -180,23 +180,13 @@ LOGGING = {
             'format': '== Mail\n\n%(mail)s\n\n== Traceback\n',
         },
     },
-    'filters': {
-        'require_debug_false': {
-            '()': 'django.utils.log.RequireDebugFalse',
-        },
-        'require_debug_true': {
-            '()': 'django.utils.log.RequireDebugTrue',
-        },
-    },
     'handlers': {
         'console': {
             'level': 'DEBUG',
-            'filters': ['require_debug_true'],
             'class': 'logging.StreamHandler',
         },
         'mail_admins': {
             'level': 'ERROR',
-            'filters': ['require_debug_false'],
             'class': 'django.utils.log.AdminEmailHandler',
             'formatter': 'email',
             'include_html': True,
```

**Comment by stephenfin** [comment]
I've checked and `django.utils.log.RequireDebugTrue` is [definitely present in Django 1.10](https://github.com/django/django/blob/1.10/django/utils/log.py#L156-L158). I imagine this is a misconfiguration with virtualenvs or something similar. I'm happy to help you work through this if so but I'm going to close this as NOTABUG.
