### ISSUE TITLE
v2.1.0: Fails to migrate on Debian Stretch

### ISSUE THREAD

**Issue by charlemagnelasse** [getpatchwork/patchwork#193]
# ./manage.py migrate
    Traceback (most recent call last):
      File "./manage.py", line 11, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
        utility.execute()
      File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 342, in execute
        self.check()
      File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
        include_deployment_checks=include_deployment_checks,
      File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
        issues.extend(super(Command, self)._run_checks(**kwargs))
      File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
        return checks.run_checks(**kwargs)
      File "/usr/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/usr/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
        return check_resolver(resolver)
      File "/usr/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
        for pattern in resolver.url_patterns:
      File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/usr/lib/python2.7/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/usr/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/usr/lib/python2.7/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
        return import_module(self.urlconf_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/opt/patchwork/patchwork/urls.py", line 214, in <module>
        from patchwork.api import bundle as api_bundle_views  # noqa
      File "/opt/patchwork/patchwork/api/bundle.py", line 27, in <module>
        from patchwork.api.filters import BundleFilterSet
      File "/opt/patchwork/patchwork/api/filters.py", line 23, in <module>
        from django_filters.rest_framework import FilterSet
    ImportError: No module named rest_framework

**Comment by charlemagnelasse** [comment]
Yes, django-filters 0.13.0-1 is installed. This should be more than enough according to the docs

**Comment by charlemagnelasse** [comment]
No, was not able to fix it up. When I tried to install the packages from testing, the server completely broke and I had to spend my summer vacation repairing the server again (at the end do a reinstall and switch to an older version of the database content).

**Comment by stephenfin** [comment]
Sorry to hear that. Would it be beneficial to work on these issues so or would it be possible to install the dependencies from PyPI (possibly via a virtualenv)?

**Comment by stephenfin** [comment]
I don't think there's much more we can do here so closing this. Thankfully the latest Debian stable has a much more recent version of this package.
