### ISSUE TITLE
[v2.1, v2.2] Postgres role 'nobody' doesn't have sufficient permissions for patch delegation via email (permission denied for relation auth_user)

### ISSUE THREAD

**Issue by alialnu** [getpatchwork/patchwork#365]
If a submission has the hint header `X-Patchwork-Delegate`, Patchwork will crash while processing it using the Postgres role `nobody`.

```
$ cat mbox | sudo -u nobody -- /path/to/patchwork/patchwork/bin/parsemail.sh

Error when parsing incoming email: ProgrammingError('permission denied for relation auth_user\n',)
Traceback (most recent call last):
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InsufficientPrivilege: permission denied for relation auth_user


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/patchwork/patchwork/management/commands/parsemail.py", line 66, in handle
    result = parse_mail(mail, options['list_id'])
  File "/path/to/patchwork/patchwork/parser.py", line 1095, in parse_mail
    delegate = find_delegate_by_header(mail)
  File "/path/to/patchwork/patchwork/parser.py", line 1015, in find_delegate_by_header
    return User.objects.get(email__iexact=delegate_email)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/path/to/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied for relation auth_user
```

My DB driver is Postgres.
The sql file [grant-all.postgres.sql](https://github.com/getpatchwork/patchwork/blob/master/lib/sql/grant-all.postgres.sql) gives no permissions on the relation `auth_user` to the `nobody` role. Should it?
Granting the role `SELECT` privileges to the `auth_user` relation solves this issue, but it seems like more permissions than `nobody` should have. What do you think?

**Comment by uajain** [comment]
I can confirm the issue on v2.2.0

**Comment by stephenfin** [comment]
Fix proposed at https://lists.ozlabs.org/pipermail/patchwork/2020-November/006846.html

**Comment by alialnu** [comment]
> 
> 
> Fix proposed at https://lists.ozlabs.org/pipermail/patchwork/2020-November/006846.html

Thanks @stephenfin
