### ISSUE TITLE
TypeError: unsupported operand type(s) for &: 'type' and 'type'

### ISSUE THREAD

**Issue by gleb498** [getpatchwork/patchwork#370]
When I try to check that all requirements are met using the check command of the manage.py I got the following error:

```
user@ws-365:/opt/patchwork$ $ sudo -u www-data python3 manage.py check
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python3/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/patchwork/patchwork/urls.py", line 181, in <module>
    from patchwork.api import bundle as api_bundle_views  # noqa
  File "/opt/patchwork/patchwork/api/bundle.py", line 116, in <module>
    class BundleMixin(object):
  File "/opt/patchwork/patchwork/api/bundle.py", line 118, in BundleMixin
    permission_classes = [PatchworkPermission & BundlePermission]
TypeError: unsupported operand type(s) for &: 'type' and 'type'
```
Problem was detected on Ubuntu 18.04.4 LTS

**Comment by stephenfin** [comment]
I can't reproduce this on a Fedora 32 host using the `py36-django30` virtualenv created with `tox` (details below). I'm going to close as not an issue. If you can still reproduce this, please reopen the issue with details of your packages. I'd say that's the most likely culprit.

```
(py36-django30)$ pip freeze
asgiref==3.3.1
attrs==20.3.0
Django==3.0.11
django-filter==2.4.0
djangorestframework==3.12.2
importlib-metadata==3.1.0
isodate==0.6.0
jsonschema==3.2.0
lazy-object-proxy==1.5.2
more-itertools==8.6.0
mysqlclient==2.0.1
openapi-core @ https://github.com/p1c2u/openapi-core/archive/97ec8c796746f72ef3298fe92078b5f80e1f66f7.tar.gz
openapi-schema-validator==0.1.1
openapi-spec-validator==0.2.9
parse==1.18.0
psycopg2-binary==2.8.6
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.4
PyYAML==5.3.1
six==1.15.0
sqlparse==0.3.1
strict-rfc3339==0.7
Werkzeug==1.0.1
zipp==3.4.0
```
