### ISSUE TITLE
`Internal Server Error` when updating a patch via REST

### ISSUE THREAD

**Issue by matttbe** [getpatchwork/patchwork#423]
Hello,

First, thank you for working on this very useful tool!

I'm a user of Patchwork on patchwork.kernel.org with an account allowing me to modify status for one project.

On kernel.org, they are using the version 2.2.5 (recently updated?). Since yesterday, I'm not able to update patches from the command line with `git-pw`:

```
$ git-pw --debug patch update --delegate martineau 12447551
2021-08-20 09:10:50,747 - git_pw.patch - DEBUG - Updating patch: id=12447551, commit_ref=None, state=None, archived=None
2021-08-20 09:10:50,751 - git_pw.config - DEBUG - Retrieved 'server' setting from git-config
2021-08-20 09:10:50,752 - git_pw.config - DEBUG - Retrieved 'server' setting from cache
2021-08-20 09:10:50,756 - git_pw.config - DEBUG - Retrieved 'project' setting from git-config
2021-08-20 09:10:50,756 - git_pw.config - DEBUG - Retrieved 'project' setting from cache
2021-08-20 09:10:50,756 - git_pw.config - DEBUG - Retrieved 'project' setting from cache
2021-08-20 09:10:50,756 - git_pw.config - DEBUG - Retrieved 'project' setting from cache
2021-08-20 09:10:50,757 - git_pw.api - DEBUG - GET https://patchwork.kernel.org/api/1.1/users/
2021-08-20 09:10:50,761 - git_pw.config - DEBUG - Retrieved 'token' setting from git-config
2021-08-20 09:10:50,761 - git_pw.config - DEBUG - Retrieved 'token' setting from cache
2021-08-20 09:10:50,764 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): patchwork.kernel.org:443
2021-08-20 09:10:51,454 - urllib3.connectionpool - DEBUG - https://patchwork.kernel.org:443 "GET /api/1.1/users/?q=martineau&project=mptcp HTTP/1.1" 200 169
2021-08-20 09:10:51,455 - git_pw.api - DEBUG - Got response
2021-08-20 09:10:51,456 - git_pw.config - DEBUG - Retrieved 'server' setting from cache
2021-08-20 09:10:51,456 - git_pw.config - DEBUG - Retrieved 'server' setting from cache
2021-08-20 09:10:51,456 - git_pw.api - DEBUG - PATCH https://patchwork.kernel.org/api/1.1/patches/12447551/, data=[('delegate', 127271)]
2021-08-20 09:10:51,456 - git_pw.config - DEBUG - Retrieved 'token' setting from cache
2021-08-20 09:10:51,456 - git_pw.config - DEBUG - Retrieved 'token' setting from cache
2021-08-20 09:10:51,458 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): patchwork.kernel.org:443
2021-08-20 09:10:52,136 - urllib3.connectionpool - DEBUG - https://patchwork.kernel.org:443 "PATCH /api/1.1/patches/12447551/ HTTP/1.1" 500 27
2021-08-20 09:10:52,138 - git_pw.api - ERROR - Server error. Please report this issue to https://github.com/getpatchwork/patchwork
Traceback (most recent call last):
  File "/usr/local/bin/git-pw", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/git_pw/patch.py", line 196, in update_cmd
    patch = api.update('patches', patch_id, data)
  File "/usr/local/lib/python3.9/dist-packages/git_pw/api.py", line 372, in update
    return _patch(url, data).json()
  File "/usr/local/lib/python3.9/dist-packages/git_pw/api.py", line 176, in _patch
    _handle_error('update', exc)
  File "/usr/local/lib/python3.9/dist-packages/git_pw/api.py", line 174, in _patch
    rsp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://patchwork.kernel.org/api/1.1/patches/12447551/
```

I was going to report this issue to kernel.org sysadmins but the messages above suggest me to report it here.
Please note that I can `curl` the last URL mentioned above without issues. From what I see in `git_pw/patch.py:196`, it is doing an `update` operation, so not a `GET` I guess.

Do you think it is due to Patchwork itself or the way it has been deployed and configured?

**Comment by matttbe** [comment]
Something I just noticed: I get the "internal server error" but the status has been properly updated on the WebUI side!
Maybe an issue when trying to retrieve the new status just after having updated it?

**Comment by stephenfin** [comment]
Thank you for the report. This is interesting. It's tough to figure this out without debug logs, which we'll need to get from the sysadmins for the instance. It seems you've already done this so there's not much more to be done for now, but Konstantin is free to reach out if this is something tricky.

**Comment by mricon** [comment]
This is due to /api/1.1/. I emailed the list about it, but the gist is that the following calls return 500 errors: `PATCH /api/1.1/patches/{id}/`. Switching to /api/1.2/ fixes this.

**Comment by daxtens** [comment]
Having a look

>

**Comment by daxtens** [comment]
A fix is on the list and a new release should be cut in the next few days.
Thank you for your bug report and for using patchwork.

**Comment by matttbe** [comment]
Thank you for the workaround which works for me for my use so far. And thank you for the fixes!

**Comment by mricon** [comment]
Hotpatched on patchwork.kernel.org.
