### ISSUE TITLE
test failures due to Django 4.0 release

### ISSUE THREAD

**Issue by vicamo** [getpatchwork/patchwork#443]
While the dependencies in `tox.ini` has `django32: django>=3.2.0`, it will install newly released Django v4.0 on supported python versions (v3.8 and v3.9), and some test cases therefore break:
```
  py38-django32 installdeps: -r/home/runner/work/patchwork/patchwork/requirements-test.txt, django>=3.2.0, djangorestframework~=3.12.0, django-filter~=21.1.0
  py38-django32 installed: asgiref==3.4.1,attrs==21.2.0,backports.zoneinfo==0.2.1,dictpath==0.1.3,Django==4.0,django-filter==21.1,djangorestframework==3.12.4,isodate==0.6.0,jsonschema==3.2.0,lazy-object-proxy==1.6.0,more-itertools==8.12.0,mysqlclient==2.0.3,openapi-core==0.14.2,openapi-schema-validator==0.1.5,openapi-spec-validator==0.3.1,parse==1.19.0,psycopg2-binary==2.9.2,pyrsistent==0.18.0,python-dateutil==2.8.2,PyYAML==6.0,six==1.16.0,sqlparse==0.4.2,tblib==1.7.0,Werkzeug==2.0.2
  py38-django32 run-test-pre: PYTHONHASHSEED='191006487'
  py38-django32 run-test: commands[0] | python /home/runner/work/patchwork/patchwork/manage.py test --noinput --parallel -- patchwork
  /home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/conf/__init__.py:199: RemovedInDjango50Warning: The default value of USE_TZ will change from False to True in Django 5.0. Set USE_TZ to False in your project settings if you want to keep the current default behavior.
    warnings.warn(
  Found 464 test(s).
  /home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'patchwork' defines default_app_config = 'patchwork.apps.PatchworkAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
  Creating test database for alias 'default'...
  Cloning test database for alias 'default'...
  Cloning test database for alias 'default'...
  Destroying test database for alias 'default'...
  Destroying test database for alias 'default'...
  Destroying test database for alias 'default'...
  Traceback (most recent call last):
    File "manage.py", line 12, in <module>
      execute_from_command_line(sys.argv)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
      utility.execute()
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
      super().run_from_argv(argv)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/base.py", line 373, in run_from_argv
      self.execute(*args, **cmd_options)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/base.py", line 417, in execute
      output = self.handle(*args, **options)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/commands/test.py", line 59, in handle
      failures = test_runner.run_tests(test_labels)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/test/runner.py", line 933, in run_tests
      self.run_checks(databases)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/test/runner.py", line 852, in run_checks
      call_command('check', verbosity=self.verbosity, databases=databases)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/__init__.py", line 187, in call_command
      return command.execute(*args, **defaults)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/base.py", line 417, in execute
      output = self.handle(*args, **options)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/commands/check.py", line 63, in handle
      self.check(
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/management/base.py", line 438, in check
      all_issues = checks.run_checks(
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/checks/registry.py", line 77, in run_checks
      new_errors = check(app_configs=app_configs, databases=databases)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
      return check_resolver(resolver)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
      return check_method()
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/urls/resolvers.py", line 446, in check
      for pattern in self.url_patterns:
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
      res = instance.__dict__[self.name] = self.func(instance)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/urls/resolvers.py", line 632, in url_patterns
      patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
      res = instance.__dict__[self.name] = self.func(instance)
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/django/urls/resolvers.py", line 625, in urlconf_module
      return import_module(self.urlconf_name)
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 843, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/home/runner/work/patchwork/patchwork/patchwork/urls.py", line 232, in <module>
      from patchwork.api import bundle as api_bundle_views  # noqa
    File "/home/runner/work/patchwork/patchwork/patchwork/api/__init__.py", line 6, in <module>
      from rest_framework.fields import empty
    File "/home/runner/work/patchwork/patchwork/.tox/py38-django32/lib/python3.8/site-packages/rest_framework/fields.py", line 32, in <module>
      from pytz.exceptions import InvalidTimeError
  ModuleNotFoundError: No module named 'pytz'
  ERROR: InvocationError for command /home/runner/work/patchwork/patchwork/.tox/py38-django32/bin/python manage.py test --noinput --parallel -- patchwork (exited with code 1)
___________________________________ summary ____________________________________
  py38-django22: commands succeeded
  py38-django31: commands succeeded
ERROR:   py38-django32: commands failed
```
See https://github.com/vicamo/patchwork/actions/runs/1549038213 for test runs.

**Comment by vicamo** [comment]
And it's not sufficient to fix this by installing pytz:
```
  py38-django40 installdeps: -r/home/runner/work/patchwork/patchwork/requirements-test.txt, django~=4.0.0, djangorestframework~=3.12.0, django-filter~=21.1.0, pytz>=2021.3
  py38-django40 installed: asgiref==3.4.1,attrs==21.2.0,backports.zoneinfo==0.2.1,dictpath==0.1.3,Django==4.0,django-filter==21.1,djangorestframework==3.12.4,isodate==0.6.0,jsonschema==3.2.0,lazy-object-proxy==1.6.0,more-itertools==8.12.0,mysqlclient==2.0.3,openapi-core==0.14.2,openapi-schema-validator==0.1.5,openapi-spec-validator==0.3.1,parse==1.19.0,psycopg2-binary==2.9.2,pyrsistent==0.18.0,python-dateutil==2.8.2,pytz==2021.3,PyYAML==6.0,six==1.16.0,sqlparse==0.4.2,tblib==1.7.0,Werkzeug==2.0.2
  py38-django40 run-test-pre: PYTHONHASHSEED='1236901002'
  py38-django40 run-test: commands[0] | python /home/runner/work/patchwork/patchwork/manage.py test --noinput --parallel -- patchwork
  /home/runner/work/patchwork/patchwork/.tox/py38-django40/lib/python3.8/site-packages/django/conf/__init__.py:199: RemovedInDjango50Warning: The default value of USE_TZ will change from False to True in Django 5.0. Set USE_TZ to False in your project settings if you want to keep the current default behavior.
    warnings.warn(
  Found 636 test(s).
  /home/runner/work/patchwork/patchwork/.tox/py38-django40/lib/python3.8/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'patchwork' defines default_app_config = 'patchwork.apps.PatchworkAppConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
  Creating test database for alias 'default'...
  System check identified no issues (0 silenced).
  Cloning test database for alias 'default'...
  Cloning test database for alias 'default'...
  ..................................................................................................................................................................................................................................................................................................................................F........................................................................................................................................................................................................................s................................................................................................
  ======================================================================
  FAIL: test_duplicated (patchwork.tests.test_series.BaseSeriesTest)
  Series received on multiple mailing lists.
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
      yield
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/case.py", line 676, in run
      self._callTestMethod(testMethod)
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
      method()
    File "/home/runner/work/patchwork/patchwork/patchwork/tests/test_series.py", line 198, in test_duplicated
      self.assertSerialized(patches_a + patches_b, [2, 2])
    File "/home/runner/work/patchwork/patchwork/patchwork/tests/test_series.py", line 79, in assertSerialized
      self.assertEqual(patch.series, series[idx])
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
      assertion_func(first, second, msg=msg)
    File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
      raise self.failureException(msg)
  AssertionError: <Series: [1/2] test: Add some lorem ipsum> != <Series: [1/2] test: Add some lorem ipsum>
  
  ----------------------------------------------------------------------
  Ran 636 tests in 42.754s
  
  FAILED (failures=1, skipped=1)
  Destroying test database for alias 'default'...
  Destroying test database for alias 'default'...
  Destroying test database for alias 'default'...
  ERROR: InvocationError for command /home/runner/work/patchwork/patchwork/.tox/py38-django40/bin/python manage.py test --noinput --parallel -- patchwork (exited with code 1)
___________________________________ summary ____________________________________
  py38-django22: commands succeeded
  py38-django31: commands succeeded
  py38-django32: commands succeeded
ERROR:   py38-django40: commands failed
```
See https://github.com/vicamo/patchwork/actions/runs/1549089646

**Comment by vicamo** [comment]
https://lists.ozlabs.org/pipermail/patchwork/2021-December/007264.html

**Comment by stephenfin** [comment]
And I see that's exactly what you've proposed. Thanks!
