### ISSUE TITLE
manage.py collectstatic fails with a UnicodeDecodeError exception

### ISSUE THREAD

**Issue by alialnu** [getpatchwork/patchwork#460]
```
$ manage.py collectstatic --clear -v3 --no-input
[..]
Post-processed 'fonts/glyphicons-halflings-regular.eot' as 'fonts/glyphicons-halflings-regular.7ad17c6085de.eot'
Post-processed 'fonts/glyphicons-halflings-regular.svg' as 'fonts/glyphicons-halflings-regular.32941d633004.svg'
Traceback (most recent call last):
  File "/path/to/patchwork/manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/path/to/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/path/to/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path/to/venv/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/path/to/venv/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/path/to/venv/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/path/to/venv/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 148, in collect
    for original_path, processed_path, processed in processor:
  File "/path/to/venv/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 447, in post_process
    yield from super().post_process(*args, **kwargs)
  File "/path/to/venv/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 260, in post_process
    for name, hashed_name, processed, _ in self._post_process(
  File "/path/to/venv/lib/python3.9/site-packages/django/contrib/staticfiles/storage.py", line 323, in _post_process
    content = original_file.read().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 158: invalid start byte
```

This occurs because of the copyright symbol in [htdocs/js/jquery.tablednd.js:4](https://github.com/getpatchwork/patchwork/blob/9a95423970eb29c7e9ce51a8f717a5c262d3fe87/htdocs/js/jquery.tablednd.js#L4).

OS: Debian 11
Python: 3.9.2
Django: 4.0.4
Patchwork: master (9a95423970eb29c7e9ce51a8f717a5c262d3fe87)

The exception doesn't reproduce on the same environment with Patchwork version stable/2.2 (d357c267637a4d9858f95ff815d54bdb0b9417ad) and Django 2.2.28.

**Comment by stephenfin** [comment]
I don't think there's much we can do here. This sounds like a bug in Django itself. However, the good news is that we recently updated the various JS dependencies (change a741c957078b55c9b990aa75760d02786669d691) so you shouldn't see this issue in the next release. You could choose to (partially?) backport that change if you like, though I consider it too feature'y to do myself.
