### ISSUE TITLE
State matching query does not exist.

### ISSUE THREAD

**Issue by traxys** [getpatchwork/patchwork#520]
I am trying to deploy a patchwork instance, and I hit a roadblock I don't really know how to fix.

I am deploying a production instance on a RHEL8 server. I installed the server as per the production instructions (installing python dependencies using pip), just leaving the `DEBUG = True` and `ALLOW_HOSTS = ['*']` as I don't have a hostname.

I fiddled quite a bit with the file permissions to make it work, so there may be some issues there, but when I recieve an email from postfix I have the following exception:

```
n parsing incoming email: DoesNotExist('State matching query does not exist.',)
Traceback (most recent call last):
  File "/opt/patchwork/patchwork/management/commands/parsemail.py", line 58, in handle
    result = parse_mail(mail, options['list_id'])
  File "/opt/patchwork/patchwork/parser.py", line 1114, in parse_mail
    state=find_state(mail))
  File "/opt/patchwork/patchwork/parser.py", line 981, in find_state
    return get_default_initial_patch_state()
  File "/opt/patchwork/patchwork/models.py", line 263, in get_default_initial_patch_state
    return State.objects.get(ordering=0)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 431, in get
    self.model._meta.object_name
patchwork.models.State.DoesNotExist: State matching query does not exist.
```

Any idea on what step I missed ?

**Comment by stephenfin** [comment]
Did you load the fixtures?

```
python3 manage.py loaddata default_tags default_states
```

This is in the [Final steps](https://patchwork.readthedocs.io/en/latest/deployment/installation/#final-steps) section of the docs.

**Comment by traxys** [comment]
Thank you very much, I really thought I had done those commands, must failed my copy paste.

I then encountered:
```
Traceback (most recent call last):
  File "/opt/patchwork/patchwork/management/commands/parsemail.py", line 58, in handle
    result = parse_mail(mail, options['list_id'])
  File "/opt/patchwork/patchwork/parser.py", line 1114, in parse_mail
    state=find_state(mail))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/patchwork/patchwork/models.py", line 501, in save
    super(Patch, self).save(**kwargs)
  File "/opt/patchwork/patchwork/models.py", line 346, in save
    super(EmailMixin, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: permission denied for sequence patchwork_submission_id_seq
```

That I solved with a "GRANT SELECT, UPDATE ON patchwork_submission_id_seq TO nobody;". Now I am able to recieve mails!
