### ISSUE TITLE
"Table 'patchwork.patchwork_state' doesn't exist" on fresh installation

### ISSUE THREAD

**Issue by Thynix** [getpatchwork/patchwork#67]
I'm attempting to set up Patchwork by following the [README instructions](https://github.com/getpatchwork/patchwork#development-installation) on using
Docker. Upon running `docker-compose up` I eventually get: ([Here](https://gist.github.com/Thynix/9cac522f4980d8020d2c497033848acf) is the full output.)

```
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
web_1  |     return self.cursor.execute(query, args)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 250, in execute
web_1  |     self.errorhandler(self, exc, value)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
web_1  |     raise errorvalue
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 247, in execute
web_1  |     res = self._query(query)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 411, in _query
web_1  |     rowcount = self._do_query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
web_1  |     db.query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 270, in query
web_1  |     _mysql.connection.query(self, query)
web_1  | _mysql_exceptions.ProgrammingError: (1146, "Table 'patchwork.patchwork_state' doesn't exist")
web_1  | 
web_1  | The above exception was the direct cause of the following exception:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/home/patchwork/patchwork/manage.py", line 11, in <module>
web_1  |     execute_from_command_line(sys.argv)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
web_1  |     utility.execute()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 359, in execute
web_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 294, in run_from_argv
web_1  |     self.execute(*args, **cmd_options)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 342, in execute
web_1  |     self.check()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 374, in check
web_1  |     include_deployment_checks=include_deployment_checks,
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
web_1  |     issues.extend(super(Command, self)._run_checks(**kwargs))
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 361, in _run_checks
web_1  |     return checks.run_checks(**kwargs)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 81, in run_checks
web_1  |     new_errors = check(app_configs=app_configs)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
web_1  |     return check_resolver(resolver)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
web_1  |     for pattern in resolver.url_patterns:
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 35, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
web_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 35, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
web_1  |     return import_module(self.urlconf_name)
web_1  |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
web_1  |   File "/home/patchwork/patchwork/patchwork/urls.py", line 155, in <module>
web_1  |     from patchwork.api import check as api_check_views
web_1  |   File "/home/patchwork/patchwork/patchwork/api/check.py", line 21, in <module>
web_1  |     from rest_framework.generics import ListCreateAPIView
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 25, in <module>
web_1  |     class GenericAPIView(views.APIView):
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 47, in GenericAPIView
web_1  |     pagination_class = api_settings.DEFAULT_PAGINATION_CLASS
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/settings.py", line 220, in __getattr__
web_1  |     val = perform_import(val, attr)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/settings.py", line 163, in perform_import
web_1  |     return import_from_string(val, setting_name)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/settings.py", line 177, in import_from_string
web_1  |     module = importlib.import_module(module_path)
web_1  |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "/home/patchwork/patchwork/patchwork/api/base.py", line 29, in <module>
web_1  |     for x in State.objects.all()]
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 256, in __iter__
web_1  |     self._fetch_all()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
web_1  |     self._result_cache = list(self.iterator())
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 54, in __iter__
web_1  |     results = compiler.execute_sql()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
web_1  |     cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 79, in execute
web_1  |     return super(CursorDebugWrapper, self).execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 94, in __exit__
web_1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
web_1  |     raise value.with_traceback(tb)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
web_1  |     return self.cursor.execute(query, args)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 250, in execute
web_1  |     self.errorhandler(self, exc, value)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
web_1  |     raise errorvalue
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 247, in execute
web_1  |     res = self._query(query)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 411, in _query
web_1  |     rowcount = self._do_query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
web_1  |     db.query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 270, in query
web_1  |     _mysql.connection.query(self, query)
web_1  | django.db.utils.ProgrammingError: (1146, "Table 'patchwork.patchwork_state' doesn't exist")
patchwork_web_1 exited with code 1
```

I found a problem that [looked similar](https://lists.ozlabs.org/pipermail/patchwork/2016-May/002817.html), applied the patch, and ran `docker-container build` and `docker-container up` again but it did not change this behavior.

I have encountered this on both Arch Linux with Docker version 1.12.5, build 7392c3b0ce and docker-compose 1.9.0-1, and Ubuntu 16.04.1 LTS with Docker version 1.12.5, build 7392c3b and docker-compose version 1.5.2, build unknown.

Is there more information I can provide, or other things I can try?

**Comment by stephenfin** [comment]
Fixed on `master`
