### ISSUE TITLE
docker recipe fails in Fedora24 and 25.

### ISSUE THREAD

**Issue by danilocesar** [getpatchwork/patchwork#79]
I followed the instructions to create a docker container but it looks like it's failing with the following message:

```shell
$$ docker-compose up

Creating patchwork_db_1
Creating patchwork_web_1
Attaching to patchwork_db_1, patchwork_web_1
db_1   | Initializing database
db_1   | 2017-02-06T16:53:06.516312Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
web_1  | MySQL seems not to be connected, or the patchwork user is broken
web_1  | MySQL may still be starting. Waiting 5 seconds.
db_1   | 2017-02-06T16:53:06.812906Z 0 [Warning] InnoDB: New log files created, LSN=45790
db_1   | 2017-02-06T16:53:06.857103Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
db_1   | 2017-02-06T16:53:06.918425Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: bba628b7-ec8c-11e6-a9fe-0242ac110002.
db_1   | 2017-02-06T16:53:06.918988Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
db_1   | 2017-02-06T16:53:06.919183Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1   | 2017-02-06T16:53:07.188686Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:07.188705Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:07.188714Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:07.188719Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:07.188743Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | Database initialized
db_1   | Initializing certificates
db_1   | Generating a 2048 bit RSA private key
db_1   | ................................+++
db_1   | .............................................................................................................................................+++
db_1   | unable to write 'random state'
db_1   | writing new private key to 'ca-key.pem'
db_1   | -----
db_1   | Generating a 2048 bit RSA private key
db_1   | .........+++
db_1   | ..+++
db_1   | unable to write 'random state'
db_1   | writing new private key to 'server-key.pem'
db_1   | -----
db_1   | Generating a 2048 bit RSA private key
db_1   | ........................+++
db_1   | .....................+++
db_1   | unable to write 'random state'
db_1   | writing new private key to 'client-key.pem'
db_1   | -----
db_1   | Certificates initialized
db_1   | MySQL init process in progress...
db_1   | 2017-02-06T16:53:09.252946Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1   | 2017-02-06T16:53:09.253624Z 0 [Note] mysqld (mysqld 5.7.17) starting as process 83 ...
db_1   | 2017-02-06T16:53:09.255303Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1   | 2017-02-06T16:53:09.255314Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1   | 2017-02-06T16:53:09.255317Z 0 [Note] InnoDB: Uses event mutexes
db_1   | 2017-02-06T16:53:09.255320Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1   | 2017-02-06T16:53:09.255323Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
db_1   | 2017-02-06T16:53:09.255324Z 0 [Note] InnoDB: Using Linux native AIO
db_1   | 2017-02-06T16:53:09.255451Z 0 [Note] InnoDB: Number of pools: 1
db_1   | 2017-02-06T16:53:09.255530Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1   | 2017-02-06T16:53:09.256250Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1   | 2017-02-06T16:53:09.260313Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1   | 2017-02-06T16:53:09.261239Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1   | 2017-02-06T16:53:09.272335Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1   | 2017-02-06T16:53:09.277069Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1   | 2017-02-06T16:53:09.277111Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1   | 2017-02-06T16:53:09.308105Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1   | 2017-02-06T16:53:09.308728Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1   | 2017-02-06T16:53:09.308736Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1   | 2017-02-06T16:53:09.308959Z 0 [Note] InnoDB: Waiting for purge to start
db_1   | 2017-02-06T16:53:09.359067Z 0 [Note] InnoDB: 5.7.17 started; log sequence number 2534561
db_1   | 2017-02-06T16:53:09.359178Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1   | 2017-02-06T16:53:09.359232Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1   | 2017-02-06T16:53:09.360137Z 0 [Note] InnoDB: Buffer pool(s) load completed at 170206 16:53:09
db_1   | 2017-02-06T16:53:09.361611Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1   | 2017-02-06T16:53:09.361721Z 0 [Warning] CA certificate ca.pem is self signed.
db_1   | 2017-02-06T16:53:09.370542Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:09.370560Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:09.370571Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:09.370579Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:09.371264Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:09.373859Z 0 [Note] Event Scheduler: Loaded 0 events
db_1   | 2017-02-06T16:53:09.373936Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
db_1   | 2017-02-06T16:53:09.373941Z 0 [Note] Beginning of list of non-natively partitioned tables
db_1   | 2017-02-06T16:53:09.378406Z 0 [Note] End of list of non-natively partitioned tables
db_1   | 2017-02-06T16:53:09.378461Z 0 [Note] mysqld: ready for connections.
db_1   | Version: '5.7.17'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
db_1   | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1   | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1   | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1   | 2017-02-06T16:53:11.021995Z 5 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.022008Z 5 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.022018Z 5 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.022022Z 5 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.022041Z 5 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | mysql: [Warning] Using a password on the command line interface can be insecure.
db_1   | mysql: [Warning] Using a password on the command line interface can be insecure.
db_1   | 2017-02-06T16:53:11.026360Z 7 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.026373Z 7 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.026385Z 7 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.026390Z 7 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:11.026452Z 7 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 
db_1   | 2017-02-06T16:53:11.027037Z 0 [Note] Giving 0 client threads a chance to die gracefully
db_1   | 2017-02-06T16:53:11.027046Z 0 [Note] Shutting down slave threads
db_1   | 2017-02-06T16:53:11.027051Z 0 [Note] Forcefully disconnecting 0 remaining clients
db_1   | 2017-02-06T16:53:11.027055Z 0 [Note] Event Scheduler: Purging the queue. 0 events
db_1   | 2017-02-06T16:53:11.027078Z 0 [Note] Binlog end
db_1   | 2017-02-06T16:53:11.027536Z 0 [Note] Shutting down plugin 'ngram'
db_1   | 2017-02-06T16:53:11.027542Z 0 [Note] Shutting down plugin 'BLACKHOLE'
db_1   | 2017-02-06T16:53:11.027544Z 0 [Note] Shutting down plugin 'partition'
db_1   | 2017-02-06T16:53:11.027546Z 0 [Note] Shutting down plugin 'ARCHIVE'
db_1   | 2017-02-06T16:53:11.027550Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
db_1   | 2017-02-06T16:53:11.027552Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
db_1   | 2017-02-06T16:53:11.027556Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
db_1   | 2017-02-06T16:53:11.027558Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
db_1   | 2017-02-06T16:53:11.027561Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
db_1   | 2017-02-06T16:53:11.027563Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
db_1   | 2017-02-06T16:53:11.027565Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
db_1   | 2017-02-06T16:53:11.027568Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
db_1   | 2017-02-06T16:53:11.027570Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
db_1   | 2017-02-06T16:53:11.027573Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
db_1   | 2017-02-06T16:53:11.027575Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
db_1   | 2017-02-06T16:53:11.027578Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
db_1   | 2017-02-06T16:53:11.027582Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
db_1   | 2017-02-06T16:53:11.027585Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
db_1   | 2017-02-06T16:53:11.027587Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
db_1   | 2017-02-06T16:53:11.027590Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
db_1   | 2017-02-06T16:53:11.027592Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
db_1   | 2017-02-06T16:53:11.027595Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
db_1   | 2017-02-06T16:53:11.027597Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
db_1   | 2017-02-06T16:53:11.027601Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
db_1   | 2017-02-06T16:53:11.027603Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
db_1   | 2017-02-06T16:53:11.027606Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
db_1   | 2017-02-06T16:53:11.027608Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
db_1   | 2017-02-06T16:53:11.027611Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
db_1   | 2017-02-06T16:53:11.027613Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
db_1   | 2017-02-06T16:53:11.027616Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
db_1   | 2017-02-06T16:53:11.027618Z 0 [Note] Shutting down plugin 'INNODB_CMP'
db_1   | 2017-02-06T16:53:11.027620Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
db_1   | 2017-02-06T16:53:11.027623Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
db_1   | 2017-02-06T16:53:11.027625Z 0 [Note] Shutting down plugin 'INNODB_TRX'
db_1   | 2017-02-06T16:53:11.027627Z 0 [Note] Shutting down plugin 'InnoDB'
db_1   | 2017-02-06T16:53:11.027667Z 0 [Note] InnoDB: FTS optimize thread exiting.
db_1   | 2017-02-06T16:53:11.027697Z 0 [Note] InnoDB: Starting shutdown...
db_1   | 2017-02-06T16:53:11.127826Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1   | 2017-02-06T16:53:11.127983Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 170206 16:53:11
web_1  | Still cannot connect to MySQL.
web_1  | Maybe you are starting the db for the first time. Waiting 15 seconds.
db_1   | 2017-02-06T16:53:12.234116Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12167412
db_1   | 2017-02-06T16:53:12.235440Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1   | 2017-02-06T16:53:12.235449Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
db_1   | 2017-02-06T16:53:12.235453Z 0 [Note] Shutting down plugin 'MyISAM'
db_1   | 2017-02-06T16:53:12.235460Z 0 [Note] Shutting down plugin 'CSV'
db_1   | 2017-02-06T16:53:12.235463Z 0 [Note] Shutting down plugin 'MEMORY'
db_1   | 2017-02-06T16:53:12.235466Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
db_1   | 2017-02-06T16:53:12.235484Z 0 [Note] Shutting down plugin 'sha256_password'
db_1   | 2017-02-06T16:53:12.235487Z 0 [Note] Shutting down plugin 'mysql_native_password'
db_1   | 2017-02-06T16:53:12.235589Z 0 [Note] Shutting down plugin 'binlog'
db_1   | 2017-02-06T16:53:12.236508Z 0 [Note] mysqld: Shutdown complete
db_1   | 
db_1   | 
db_1   | MySQL init process done. Ready for start up.
db_1   | 
db_1   | 2017-02-06T16:53:12.413346Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1   | 2017-02-06T16:53:12.414022Z 0 [Note] mysqld (mysqld 5.7.17) starting as process 1 ...
db_1   | 2017-02-06T16:53:12.415842Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1   | 2017-02-06T16:53:12.415853Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1   | 2017-02-06T16:53:12.415855Z 0 [Note] InnoDB: Uses event mutexes
db_1   | 2017-02-06T16:53:12.415857Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1   | 2017-02-06T16:53:12.415858Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
db_1   | 2017-02-06T16:53:12.415860Z 0 [Note] InnoDB: Using Linux native AIO
db_1   | 2017-02-06T16:53:12.415983Z 0 [Note] InnoDB: Number of pools: 1
db_1   | 2017-02-06T16:53:12.416054Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1   | 2017-02-06T16:53:12.417066Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1   | 2017-02-06T16:53:12.421534Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1   | 2017-02-06T16:53:12.422610Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1   | 2017-02-06T16:53:12.433762Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1   | 2017-02-06T16:53:12.439680Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1   | 2017-02-06T16:53:12.439720Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1   | 2017-02-06T16:53:12.470067Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1   | 2017-02-06T16:53:12.470633Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1   | 2017-02-06T16:53:12.470640Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1   | 2017-02-06T16:53:12.470820Z 0 [Note] InnoDB: Waiting for purge to start
db_1   | 2017-02-06T16:53:12.520931Z 0 [Note] InnoDB: 5.7.17 started; log sequence number 12167412
db_1   | 2017-02-06T16:53:12.521044Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1   | 2017-02-06T16:53:12.521114Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1   | 2017-02-06T16:53:12.523190Z 0 [Note] InnoDB: Buffer pool(s) load completed at 170206 16:53:12
db_1   | 2017-02-06T16:53:12.523686Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1   | 2017-02-06T16:53:12.523793Z 0 [Warning] CA certificate ca.pem is self signed.
db_1   | 2017-02-06T16:53:12.524822Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1   | 2017-02-06T16:53:12.524839Z 0 [Note] IPv6 is available.
db_1   | 2017-02-06T16:53:12.524843Z 0 [Note]   - '::' resolves to '::';
db_1   | 2017-02-06T16:53:12.524855Z 0 [Note] Server socket created on IP: '::'.
db_1   | 2017-02-06T16:53:12.529255Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:12.529273Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:12.529286Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:12.529292Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:12.530578Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:12.533220Z 0 [Note] Event Scheduler: Loaded 0 events
db_1   | 2017-02-06T16:53:12.533296Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
db_1   | 2017-02-06T16:53:12.533303Z 0 [Note] Beginning of list of non-natively partitioned tables
db_1   | 2017-02-06T16:53:12.537680Z 0 [Note] End of list of non-natively partitioned tables
db_1   | 2017-02-06T16:53:12.537731Z 0 [Note] mysqld: ready for connections.
db_1   | Version: '5.7.17'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
web_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
db_1   | 2017-02-06T16:53:27.153790Z 5 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:27.153807Z 5 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:27.153820Z 5 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:27.153826Z 5 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db_1   | 2017-02-06T16:53:27.153911Z 5 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
web_1  |     return self.cursor.execute(query, args)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 250, in execute
web_1  |     self.errorhandler(self, exc, value)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
web_1  |     raise errorvalue
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 247, in execute
web_1  |     res = self._query(query)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 411, in _query
web_1  |     rowcount = self._do_query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
web_1  |     db.query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 270, in query
web_1  |     _mysql.connection.query(self, query)
web_1  | _mysql_exceptions.ProgrammingError: (1146, "Table 'patchwork.patchwork_state' doesn't exist")
web_1  | 
web_1  | The above exception was the direct cause of the following exception:
web_1  | 
web_1  | Traceback (most recent call last):
web_1  |   File "/home/patchwork/patchwork/manage.py", line 11, in <module>
web_1  |     execute_from_command_line(sys.argv)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
web_1  |     utility.execute()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 359, in execute
web_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 294, in run_from_argv
web_1  |     self.execute(*args, **cmd_options)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 342, in execute
web_1  |     self.check()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 374, in check
web_1  |     include_deployment_checks=include_deployment_checks,
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
web_1  |     issues.extend(super(Command, self)._run_checks(**kwargs))
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 361, in _run_checks
web_1  |     return checks.run_checks(**kwargs)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 81, in run_checks
web_1  |     new_errors = check(app_configs=app_configs)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
web_1  |     return check_resolver(resolver)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
web_1  |     for pattern in resolver.url_patterns:
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 35, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
web_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 35, in __get__
web_1  |     res = instance.__dict__[self.name] = self.func(instance)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
web_1  |     return import_module(self.urlconf_name)
web_1  |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
web_1  |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
web_1  |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
web_1  |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
web_1  |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
web_1  |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
web_1  |   File "/home/patchwork/patchwork/patchwork/urls.py", line 155, in <module>
web_1  |     from patchwork.api import check as api_check_views
web_1  |   File "/home/patchwork/patchwork/patchwork/api/check.py", line 21, in <module>
web_1  |     from rest_framework.generics import ListCreateAPIView
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 25, in <module>
web_1  |     class GenericAPIView(views.APIView):
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/generics.py", line 47, in GenericAPIView
web_1  |     pagination_class = api_settings.DEFAULT_PAGINATION_CLASS
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/settings.py", line 220, in __getattr__
web_1  |     val = perform_import(val, attr)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/settings.py", line 163, in perform_import
web_1  |     return import_from_string(val, setting_name)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/rest_framework/settings.py", line 177, in import_from_string
web_1  |     module = importlib.import_module(module_path)
web_1  |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
web_1  |     return _bootstrap._gcd_import(name[level:], package, level)
web_1  |   File "/home/patchwork/patchwork/patchwork/api/base.py", line 29, in <module>
web_1  |     for x in State.objects.all()]
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 256, in __iter__
web_1  |     self._fetch_all()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
web_1  |     self._result_cache = list(self.iterator())
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 54, in __iter__
web_1  |     results = compiler.execute_sql()
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
web_1  |     cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 79, in execute
web_1  |     return super(CursorDebugWrapper, self).execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 94, in __exit__
web_1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
web_1  |     raise value.with_traceback(tb)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 64, in execute
web_1  |     return self.cursor.execute(sql, params)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
web_1  |     return self.cursor.execute(query, args)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 250, in execute
web_1  |     self.errorhandler(self, exc, value)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
web_1  |     raise errorvalue
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 247, in execute
web_1  |     res = self._query(query)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 411, in _query
web_1  |     rowcount = self._do_query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/cursors.py", line 374, in _do_query
web_1  |     db.query(q)
web_1  |   File "/usr/local/lib/python3.5/dist-packages/MySQLdb/connections.py", line 270, in query
web_1  |     _mysql.connection.query(self, query)
web_1  | django.db.utils.ProgrammingError: (1146, "Table 'patchwork.patchwork_state' doesn't exist")
patchwork_web_1 exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping patchwork_db_1 ... done
```

**Comment by danilocesar** [comment]
Looks like this was already reported by https://github.com/getpatchwork/patchwork/issues/67

**Comment by stephenfin** [comment]
Indeed. I'll resolve this issue this evening :smile:
